import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set style for premium visualizations
sns.set_theme(style="whitegrid")
plt.rcParams.update({
    'font.family': 'sans-serif',
    'font.size': 12,
    'axes.labelsize': 14,
    'axes.titlesize': 16,
    'xtick.labelsize': 12,
    'ytick.labelsize': 12,
    'figure.titlesize': 18
})

# Custom color palettes
PREMIUM_PALETTE = ['#2B2D42', '#8D99AE', '#EF233C', '#D90429', '#4A90E2', '#50E3C2', '#F5A623']
sns.set_palette(sns.color_palette(PREMIUM_PALETTE))

def generate_visualizations():
    base_path = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    data_path = os.path.join(base_path, "data", "processed", "cleaned_dataset.csv")
    images_dir = os.path.join(base_path, "images")
    
    os.makedirs(images_dir, exist_ok=True)
    
    print("Loading cleaned dataset for EDA...")
    df = pd.read_csv(data_path)
    df['Date'] = pd.to_datetime(df['Date'])
    
    # 1. Product Sales Distribution (Univariate)
    print("Generating plot 1: Product Sales Distribution...")
    plt.figure(figsize=(10, 6))
    order = df['Product'].value_counts().index
    ax = sns.countplot(data=df, x='Product', order=order, palette="viridis", hue='Product', legend=False)
    plt.title("Product Order Volumes (Jan 2023 - Jun 2025)", pad=20, fontweight='bold', color='#1A202C')
    plt.xlabel("Product Category")
    plt.ylabel("Number of Orders")
    plt.tight_layout()
    plt.savefig(os.path.join(images_dir, "univariate_product_distribution.png"), dpi=300)
    plt.close()
    
    # 2. Order Status Distribution (Univariate)
    print("Generating plot 2: Order Status Distribution...")
    plt.figure(figsize=(8, 8))
    status_counts = df['OrderStatus'].value_counts()
    colors = ['#4A90E2', '#EF233C', '#F5A623', '#50E3C2', '#8D99AE']
    plt.pie(status_counts, labels=status_counts.index, autopct='%1.1f%%', startangle=140, 
            colors=colors[:len(status_counts)], wedgeprops=dict(width=0.4, edgecolor='w', linewidth=2))
    plt.title("Order Status Breakdown", pad=20, fontweight='bold', color='#1A202C')
    plt.tight_layout()
    plt.savefig(os.path.join(images_dir, "univariate_order_status.png"), dpi=300)
    plt.close()
    
    # 3. Total Revenue by Product (Bivariate)
    print("Generating plot 3: Total Revenue by Product...")
    plt.figure(figsize=(10, 6))
    prod_rev = df.groupby('Product')['TotalPrice'].sum().sort_values(ascending=False).reset_index()
    ax = sns.barplot(data=prod_rev, x='Product', y='TotalPrice', palette="mako", hue='Product', legend=False)
    plt.title("Total Revenue Generated by Product Category", pad=20, fontweight='bold', color='#1A202C')
    plt.xlabel("Product Category")
    plt.ylabel("Total Revenue (Rs.)")
    # Format y-axis labels
    import matplotlib.ticker as ticker
    ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, pos: f'Rs.{x*1e-3:.0f}k' if x >= 1e3 else f'Rs.{x:.0f}'))
    plt.tight_layout()
    plt.savefig(os.path.join(images_dir, "bivariate_revenue_by_product.png"), dpi=300)
    plt.close()
    
    # 4. Total Revenue by Referral Source (Bivariate)
    print("Generating plot 4: Total Revenue by Marketing Channel...")
    plt.figure(figsize=(10, 6))
    ref_rev = df.groupby('ReferralSource')['TotalPrice'].sum().sort_values(ascending=False).reset_index()
    ax = sns.barplot(data=ref_rev, x='ReferralSource', y='TotalPrice', palette="flare", hue='ReferralSource', legend=False)
    plt.title("Total Revenue by Marketing Channel", pad=20, fontweight='bold', color='#1A202C')
    plt.xlabel("Referral Source")
    plt.ylabel("Total Revenue (Rs.)")
    ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, pos: f'Rs.{x*1e-3:.0f}k' if x >= 1e3 else f'Rs.{x:.0f}'))
    plt.tight_layout()
    plt.savefig(os.path.join(images_dir, "bivariate_revenue_by_channel.png"), dpi=300)
    plt.close()
    
    # 5. Monthly Revenue Trend (Bivariate/Temporal)
    print("Generating plot 5: Monthly Revenue Trend...")
    df['YearMonth'] = df['Date'].dt.to_period('M')
    monthly_rev = df.groupby('YearMonth')['TotalPrice'].sum().reset_index()
    monthly_rev['YearMonth'] = monthly_rev['YearMonth'].dt.to_timestamp()
    
    plt.figure(figsize=(12, 6))
    ax = sns.lineplot(data=monthly_rev, x='YearMonth', y='TotalPrice', color='#EF233C', linewidth=3, marker='o', markersize=8)
    # Fill area under the line for modern dashboard look
    plt.fill_between(monthly_rev['YearMonth'], monthly_rev['TotalPrice'], color='#EF233C', alpha=0.15)
    
    plt.title("Monthly Sales Revenue Trend", pad=20, fontweight='bold', color='#1A202C')
    plt.xlabel("Date")
    plt.ylabel("Monthly Revenue (Rs.)")
    ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, pos: f'Rs.{x*1e-3:.0f}k' if x >= 1e3 else f'Rs.{x:.0f}'))
    plt.tight_layout()
    plt.savefig(os.path.join(images_dir, "bivariate_monthly_sales_trend.png"), dpi=300)
    plt.close()
    
    print("EDA Visualizations generated and saved to 'images/' successfully!")

if __name__ == "__main__":
    generate_visualizations()
